### ISSUE TITLE
Report errors in vite

### ISSUE THREAD

**Issue by Maicarons2022** [virtualvivek/react-windows-ui#19]
## Report errors in vite

Hello developer,  
I try using vite to complie, but reported errors form `core-js/modules/web.dom-collections.iterator.js`. 

## env
```json
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.3.0",
    "react-windows-ui": "^4.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "@vitejs/plugin-react": "^1.3.0",
    "vite": "^2.9.9"
  }
```
## Error
```bash

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js" 
                                                                              
    node_modules/react-windows-ui/dist/components/Select/index.js:1:99:       
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js");var _react=_interopRequ... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js" 

    node_modules/react-windows-ui/dist/components/TableView/index.js:1:99:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js"),require("core-js/module... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js"

    node_modules/react-windows-ui/dist/components/ImageView/index.js:1:99:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js");var _react=_interopRequ... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js"

    node_modules/react-windows-ui/dist/components/MenuBar/index.js:1:99:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js"),require("core-js/module... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js"

    node_modules/react-windows-ui/dist/components/InputText/index.js:1:21:
      1 │ "use strict";require("core-js/modules/web.dom-collections.iterator.js"),Object.defineProperty(exports,"... 
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js" 

    node_modules/react-windows-ui/dist/components/AppTheme/index.js:1:21:
      1 │ "use strict";require("core-js/modules/web.dom-collections.iterator.js"),Object.defineProperty(exports,"... 
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js"

    node_modules/react-windows-ui/dist/components/AvatarView/index.js:1:99:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js");var _react=_interopRequ... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js"

    node_modules/react-windows-ui/dist/components/NavBar/NavBar/index.js:1:99:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js");var _react=_interopRequ... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js"

    node_modules/react-windows-ui/dist/components/NavBar/NavPageContainer/index.js:1:21:
      1 │ "use strict";require("core-js/modules/web.dom-collections.iterator.js"),Object.defineProperty(exports,"... 
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/es.string.trim.js"

    node_modules/react-windows-ui/dist/components/_api/ThemeManager.js:1:99:
      1 │ ...),exports.default=void 0,require("core-js/modules/es.string.trim.js"),require("core-js/modules/es.re... 
        ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/es.string.trim.js" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/es.object.assign.js" 

    node_modules/react-windows-ui/dist/components/Link/index.js:1:99:
      1 │ ...,exports.default=void 0,require("core-js/modules/es.object.assign.js");var _react=_interopRequireDef... 
        ╵                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/es.object.assign.js" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js"

    node_modules/react-windows-ui/dist/components/NavBar/NavThemeSwitcher/index.js:1:99:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js");var _react=_interopRequ... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js"

    node_modules/react-windows-ui/dist/components/ListItem/index.js:1:99:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js");var _react=_interopRequ... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js"

    node_modules/react-windows-ui/dist/components/Alert/index.js:1:21:
      1 │ "use strict";require("core-js/modules/web.dom-collections.iterator.js"),Object.defineProperty(exports,"... 
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js"

    node_modules/react-windows-ui/dist/components/NavBar/NavSearchSuggestion/index.js:1:99:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js"),require("core-js/module... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/es.regexp.to-string.js"

    node_modules/react-windows-ui/dist/components/_api/Appearance.js:1:99:
      1 │ ...xports.default=void 0,require("core-js/modules/es.regexp.to-string.js");const getColorScheme=()=>{le... 
        ╵                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/es.regexp.to-string.js" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js" 

    node_modules/react-windows-ui/dist/components/CommandBarButton/index.js:1:99:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js");var _react=_interopRequ... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js"

    node_modules/react-windows-ui/dist/components/InputSearchSuggestion/index.js:1:99:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js"),require("core-js/module... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/es.array.sort.js" 

    node_modules/react-windows-ui/dist/components/TableView/index.js:1:158:
      1 │ ...ollections.iterator.js"),require("core-js/modules/es.array.sort.js");var _react=_interopRequireWildc... 
        ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 

  You can mark the path "core-js/modules/es.array.sort.js" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/es.array.includes.js"

    node_modules/react-windows-ui/dist/components/MenuBar/index.js:1:158:
      1 │ ...lections.iterator.js"),require("core-js/modules/es.array.includes.js"),require("core-js/modules/es.s... 
        ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/es.array.includes.js" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js" 

    node_modules/react-windows-ui/dist/components/ColorPicker/ColorPickerPalette/index.js:1:152:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js");function _getRequireWil... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js" 

    node_modules/react-windows-ui/dist/components/Gauge/index.js:1:151:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js");function _interopRequir... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js" 

    node_modules/react-windows-ui/dist/components/SplashScreen/index.js:1:152:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js");function _getRequireWil... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js"

    node_modules/react-windows-ui/dist/components/NavBar/NavSearchBox/index.js:1:152:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js");function _getRequireWil... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js"

    node_modules/react-windows-ui/dist/components/Accordion/index.js:1:152:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js");function _getRequireWil... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/web.dom-collections.iterator.js"

    node_modules/react-windows-ui/dist/components/NavBar/NavBarSubMenu/index.js:1:152:
      1 │ ...ts.default=void 0,require("core-js/modules/web.dom-collections.iterator.js");function _getRequireWil... 
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/web.dom-collections.iterator.js" as external to exclude it
  from the bundle, which will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/es.regexp.exec.js"

    node_modules/react-windows-ui/dist/components/_api/ThemeManager.js:1:144:
      1 │ ...ules/es.string.trim.js"),require("core-js/modules/es.regexp.exec.js"),require("core-js/modules/es.st... 
        ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/es.regexp.exec.js" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/es.array.includes.js"

    node_modules/react-windows-ui/dist/components/NavBar/NavSearchSuggestion/index.js:1:158:
      1 │ ...lections.iterator.js"),require("core-js/modules/es.array.includes.js"),require("core-js/modules/es.s... 
        ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/es.array.includes.js" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/es.array.includes.js"

    node_modules/react-windows-ui/dist/components/InputSearchSuggestion/index.js:1:158:
      1 │ ...lections.iterator.js"),require("core-js/modules/es.array.includes.js"),require("core-js/modules/es.s... 
        ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 

  You can mark the path "core-js/modules/es.array.includes.js" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/es.string.includes.js"

    node_modules/react-windows-ui/dist/components/MenuBar/index.js:1:206:
      1 │ ...es.array.includes.js"),require("core-js/modules/es.string.includes.js");var _react=_interopRequireWi... 
        ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/es.string.includes.js" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/es.string.replace.js" 

    node_modules/react-windows-ui/dist/components/_api/ThemeManager.js:1:189:
      1 │ ...es/es.regexp.exec.js"),require("core-js/modules/es.string.replace.js"),require("core-js/modules/es.r... 
        ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/es.string.replace.js" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/es.string.includes.js"

    node_modules/react-windows-ui/dist/components/NavBar/NavSearchSuggestion/index.js:1:206:
      1 │ ...es.array.includes.js"),require("core-js/modules/es.string.includes.js");var _react=_interopRequireWi... 
        ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/es.string.includes.js" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/es.string.includes.js" 

    node_modules/react-windows-ui/dist/components/InputSearchSuggestion/index.js:1:206:
      1 │ ...es.array.includes.js"),require("core-js/modules/es.string.includes.js");var _react=_interopRequireDe... 
        ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/es.string.includes.js" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/es.regexp.to-string.js" 

    node_modules/react-windows-ui/dist/components/_api/ThemeManager.js:1:237:
      1 │ ...s.string.replace.js"),require("core-js/modules/es.regexp.to-string.js"),require("core-js/modules/es.... 
        ╵                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/es.regexp.to-string.js" as external to exclude it from the
  bundle, which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

X [ERROR] Could not resolve "core-js/modules/es.parse-int.js" 

    node_modules/react-windows-ui/dist/components/_api/ThemeManager.js:1:287:
      1 │ .../es.regexp.to-string.js"),require("core-js/modules/es.parse-int.js");const createAlphaPrimaryColor=(... 
        ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "core-js/modules/es.parse-int.js" as external to exclude it from the bundle,
  which will remove this error. You can also surround this "require" call with a try/catch block to
  handle this failure at run-time instead of bundle-time.

10:19:57 [vite] error while updating dependencies: 
Error: Build failed with 35 errors:
node_modules/react-windows-ui/dist/components/Accordion/index.js:1:152: ERROR: Could not resolve "core-js/modules/web
.dom-collections.iterator.js"
node_modules/react-windows-ui/dist/components/Alert/index.js:1:21: ERROR: Could not resolve "core-js/modules/web.dom-
collections.iterator.js"
node_modules/react-windows-ui/dist/components/AppTheme/index.js:1:21: ERROR: Could not resolve "core-js/modules/web.d
om-collections.iterator.js"
node_modules/react-windows-ui/dist/components/AvatarView/index.js:1:99: ERROR: Could not resolve "core-js/modules/web
.dom-collections.iterator.js"
node_modules/react-windows-ui/dist/components/ColorPicker/ColorPickerPalette/index.js:1:152: ERROR: Could not resolve
 "core-js/modules/web.dom-collections.iterator.js"
...
    at failureErrorWithLog (D:\Gitlab\mccl\frontend\node_modules\esbuild\lib\main.js:1624:15)
    at D:\Gitlab\mccl\frontend\node_modules\esbuild\lib\main.js:1266:28
    at runOnEndCallbacks (D:\Gitlab\mccl\frontend\node_modules\esbuild\lib\main.js:1046:63)
    at buildResponseToResult (D:\Gitlab\mccl\frontend\node_modules\esbuild\lib\main.js:1264:7)
    at D:\Gitlab\mccl\frontend\node_modules\esbuild\lib\main.js:1377:14
    at D:\Gitlab\mccl\frontend\node_modules\esbuild\lib\main.js:678:9
    at handleIncomingPacket (D:\Gitlab\mccl\frontend\node_modules\esbuild\lib\main.js:775:9)
    at Socket.readFromStdout (D:\Gitlab\mccl\frontend\node_modules\esbuild\lib\main.js:644:7)
    at Socket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:315:12)
```

**Comment by Maicarons2022** [comment]
I find a issue about it
https://github.com/zloirock/core-js/issues/500

**Comment by Maicarons2022** [comment]
Resolved after added core-js.
```bash
yarn add --dev core-js@3
```
